# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7472ba6f7e04d1ecf90ec80c2aa35352142c3315449d6ec56646cb3610c4e762a290f877ad1e9bee55ee37f6a8bbe3f36ccaadadcb16600197f6cc9b74b2058

test:
  secret_key_base: fd7b32f6b58382c78968656801033bfb4f0d6a5b2bf9b354bfec918a54a675217c9e8ba7877a65bb6c0e334e11bf4b83f1168f68830eaff6a99b0bf9a20f419e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
